{% set name = "gh" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cli/cli/archive/v{{ version }}.tar.gz
  sha256: ffbf27c3945833dcf57f1cb16c6e8cb3de52a3a6c74c7e9539512e9a7e12b168

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - gh help

about:
  home: https://github.com/cli/cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Github CLI.
  doc_url: https://cli.github.com/
  dev_url: https://github.com/cli/cli

extra:
  recipe-maintainers:
    - rluria14
    - oblute
